import type { TimetableProject } from '../types/timetable';

export const INITIAL_MOCK_PROJECT: TimetableProject = {
  id: 'proj-1',
  name: '2026/2027 I. Félév Órarend',
  schoolName: 'Kossuth Lajos Általános Iskola',
  academicYear: '2026/2027',
  teachers: [
    {
      id: 't-1',
      name: 'Kovács Orsolya',
      shortCode: 'KO',
      color: '#3b82f6',
      maxDailyHours: 6,
      unavailableSlots: [{ day: 4, period: 7 }, { day: 4, period: 8 }],
    },
    {
      id: 't-2',
      name: 'Nagy Péter',
      shortCode: 'NP',
      color: '#ef4444',
      maxDailyHours: 5,
      unavailableSlots: [],
    },
    {
      id: 't-3',
      name: 'Szabó Éva',
      shortCode: 'SZÉ',
      color: '#10b981',
      maxDailyHours: 6,
      unavailableSlots: [{ day: 0, period: 1 }],
    },
    {
      id: 't-4',
      name: 'Tóth Gábor',
      shortCode: 'TG',
      color: '#f59e0b',
      maxDailyHours: 6,
      unavailableSlots: [],
    },
    {
      id: 't-5',
      name: 'Horváth Katalin',
      shortCode: 'HK',
      color: '#8b5cf6',
      maxDailyHours: 5,
      unavailableSlots: [],
    },
    {
      id: 't-6',
      name: 'Molnár Balázs',
      shortCode: 'MB',
      color: '#ec4899',
      maxDailyHours: 6,
      unavailableSlots: [],
    },
  ],
  classes: [
    { id: 'c-1', name: '5.A', grade: 5, color: '#3b82f6' },
    { id: 'c-2', name: '5.B', grade: 5, color: '#06b6d4' },
    { id: 'c-3', name: '6.A', grade: 6, color: '#10b981' },
    { id: 'c-4', name: '6.B', grade: 6, color: '#8b5cf6' },
  ],
  subjects: [
    { id: 's-1', name: 'Matematika', shortCode: 'MAT', color: '#3b82f6' },
    { id: 's-2', name: 'Magyar nyelv és irodalom', shortCode: 'MAGY', color: '#ef4444' },
    { id: 's-3', name: 'Történelem', shortCode: 'TÖRT', color: '#f59e0b' },
    { id: 's-4', name: 'Angol nyelv', shortCode: 'ANGOL', color: '#10b981' },
    { id: 's-5', name: 'Természettudomány', shortCode: 'TERM', color: '#8b5cf6' },
    { id: 's-6', name: 'Testnevelés', shortCode: 'TESI', color: '#ec4899' },
    { id: 's-7', name: 'Informatika / Digitális kultúra', shortCode: 'INFO', color: '#6366f1' },
  ],
  rooms: [
    { id: 'r-1', name: '101. szaktanterem', shortCode: '101' },
    { id: 'r-2', name: '102. szaktanterem', shortCode: '102' },
    { id: 'r-3', name: 'Tornaterem', shortCode: 'TORNA' },
    { id: 'r-4', name: 'Informatika terem', shortCode: 'INFO' },
  ],
  curriculum: [
    { id: 'curr-1', classId: 'c-1', subjectId: 's-1', teacherId: 't-1', roomId: 'r-1', weeklyHours: 5 },
    { id: 'curr-2', classId: 'c-1', subjectId: 's-2', teacherId: 't-2', roomId: 'r-1', weeklyHours: 5 },
    { id: 'curr-3', classId: 'c-1', subjectId: 's-3', teacherId: 't-3', roomId: 'r-1', weeklyHours: 3 },
    { id: 'curr-4', classId: 'c-1', subjectId: 's-4', teacherId: 't-4', roomId: 'r-1', weeklyHours: 4 },
    { id: 'curr-5', classId: 'c-1', subjectId: 's-5', teacherId: 't-5', roomId: 'r-1', weeklyHours: 3 },
    { id: 'curr-6', classId: 'c-1', subjectId: 's-6', teacherId: 't-6', roomId: 'r-3', weeklyHours: 3 },
    { id: 'curr-7', classId: 'c-1', subjectId: 's-7', teacherId: 't-5', roomId: 'r-4', weeklyHours: 2 },

    { id: 'curr-8', classId: 'c-2', subjectId: 's-1', teacherId: 't-1', roomId: 'r-2', weeklyHours: 5 },
    { id: 'curr-9', classId: 'c-2', subjectId: 's-2', teacherId: 't-2', roomId: 'r-2', weeklyHours: 5 },
    { id: 'curr-10', classId: 'c-2', subjectId: 's-3', teacherId: 't-3', roomId: 'r-2', weeklyHours: 3 },
    { id: 'curr-11', classId: 'c-2', subjectId: 's-4', teacherId: 't-4', roomId: 'r-2', weeklyHours: 4 },
    { id: 'curr-12', classId: 'c-2', subjectId: 's-5', teacherId: 't-5', roomId: 'r-2', weeklyHours: 3 },
    { id: 'curr-13', classId: 'c-2', subjectId: 's-6', teacherId: 't-6', roomId: 'r-3', weeklyHours: 3 },
    { id: 'curr-14', classId: 'c-2', subjectId: 's-7', teacherId: 't-5', roomId: 'r-4', weeklyHours: 2 },

    { id: 'curr-15', classId: 'c-3', subjectId: 's-1', teacherId: 't-1', roomId: 'r-1', weeklyHours: 4 },
    { id: 'curr-16', classId: 'c-3', subjectId: 's-2', teacherId: 't-2', roomId: 'r-1', weeklyHours: 4 },
    { id: 'curr-17', classId: 'c-3', subjectId: 's-3', teacherId: 't-3', roomId: 'r-1', weeklyHours: 3 },
    { id: 'curr-18', classId: 'c-3', subjectId: 's-4', teacherId: 't-4', roomId: 'r-1', weeklyHours: 4 },
    { id: 'curr-19', classId: 'c-3', subjectId: 's-5', teacherId: 't-5', roomId: 'r-1', weeklyHours: 4 },
    { id: 'curr-20', classId: 'c-3', subjectId: 's-6', teacherId: 't-6', roomId: 'r-3', weeklyHours: 3 },
    { id: 'curr-21', classId: 'c-3', subjectId: 's-7', teacherId: 't-5', roomId: 'r-4', weeklyHours: 2 },

    { id: 'curr-22', classId: 'c-4', subjectId: 's-1', teacherId: 't-1', roomId: 'r-2', weeklyHours: 4 },
    { id: 'curr-23', classId: 'c-4', subjectId: 's-2', teacherId: 't-2', roomId: 'r-2', weeklyHours: 4 },
    { id: 'curr-24', classId: 'c-4', subjectId: 's-3', teacherId: 't-3', roomId: 'r-2', weeklyHours: 3 },
    { id: 'curr-25', classId: 'c-4', subjectId: 's-4', teacherId: 't-4', roomId: 'r-2', weeklyHours: 4 },
    { id: 'curr-26', classId: 'c-4', subjectId: 's-5', teacherId: 't-5', roomId: 'r-2', weeklyHours: 4 },
    { id: 'curr-27', classId: 'c-4', subjectId: 's-6', teacherId: 't-6', roomId: 'r-3', weeklyHours: 3 },
    { id: 'curr-28', classId: 'c-4', subjectId: 's-7', teacherId: 't-5', roomId: 'r-4', weeklyHours: 2 },
  ],
  constraints: [
    {
      id: 'const-1',
      title: '5.A-ban az 1. órában ne legyen Matematika',
      type: 'NO_SUBJECT_PERIOD',
      classId: 'c-1',
      subjectId: 's-1',
      period: 1,
      priority: 'HARD',
    },
    {
      id: 'const-2',
      title: '5.B-ben a 8. órában ne legyen Magyar',
      type: 'NO_SUBJECT_PERIOD',
      classId: 'c-2',
      subjectId: 's-2',
      period: 8,
      priority: 'HARD',
    },
  ],
  slots: [],
  updatedAt: new Date().toISOString(),
};
